version: 2

sources:
  - name: olist
    database: DBT_PROJECT
    schema: OLIST_RAW
    tables:
      - name: customers
      - name: geolocation
      - name: orders
      - name: order_items
      - name: order_payment
      - name: products
      - name: product_cat
      - name: sellers
      - name: order_review

models:
  - name: src_orders
    columns:
      - name: order_id
        tests:
          - unique
          - accepted_values:
              values:
                - delivered
                - invoiced
                - completed

  - name: src_order_items
    columns:
      - name: product_id
        tests:
          - not_null



