version: 2

# Adding tests
models:
  - name: stg_orders
    description: "A staging model for orders"
    columns:
      - name: order_id
        description: "The primary key for order id"
        tests:
          - unique
          - relationships:
              field: order_id
              to: ref('stg_order_items')
      - name: order_purchase_timestamp
        tests:
          - assert_timestamp_is_past

  - name: stg_order_items
    description: "A staging model for order_items"
    tests:
      - dbt_utils.expression_is_true:
          expression: "freight_value < 25"
